### ISSUE TITLE
Mailgun Bridge

### ISSUE THREAD

**Issue by mymanga** [CloudBoost/cloudboost#35]

**Comment by nawazdhandala** [comment]
This is a good idea. We'll take this into review.

**Comment by nawazdhandala** [comment]
This is done. Please check Email section of CloudBoost App Settings.

**Comment by mymanga** [comment]
That was fast. Awesome

**Comment by gabrielAnglada** [comment]
Hi Nawaz! it would be fantastic to open an api for mailgun to sedn emails directly using Cloudboost. For example, having a method like:

`CB.CloudMailgun.send(from, to, subject, <text or html>, successCallback, errorCallback)`

Now I'm using Mandrill, and as you may know, since 2 or 3 months ago, you need to pay even for sending a few emails per month. That's why a I want to migrate to mailgun. But I have been trying to send mails vie RESTFUL and no way... Also, it is more secure to have the api key only in the server side.

Thanks!
